export const awards = [
    {
        name: "Independent of the Year",
        type: "Nominee",
        project: "INNOVATE 2024",
        label: "Awwwards",
    },
    {
        name: "Site of the day",
        type: "Awwwards",
        project: "LVXH - AMOT",
        label: "See Live",
    },
    {
        name: "Site of the day",
        type: "Awwwards",
        project: "Open Field Audio",
        label: "See Live",
    },
    {
        name: "Site of the day",
        type: "Awwwards",
        project: "ArtisanCraft",
        label: "See Live",
    },
    {
        name: "Site of the day",
        type: "Awwwards",
        project: "Disguised Edge",
        label: "See Live",
    },
    {
        name: "Site of the day",
        type: "Awwwards",
        project: "The Green Mile",
        label: "See Live",
    },
    {
        name: "Site of the day",
        type: "Awwwards",
        project: "Silent Hill",
        label: "See Live",
    },
    {
        name: "Site of the day",
        type: "Awwwards",
        project: "2023 Showcase",
        label: "See Live",
    },
    {
        name: "Site of the day",
        type: "Awwwards",
        project: "Digital Excellence Awards",
        label: "Vacuum",
    },
    {
        name: "Site of the day",
        type: "Awwwards",
        project: "Harmonic Pitch",
        label: "See Live",
    },
    {
        name: "Site of the day",
        type: "Awwwards",
        project: "ShadowLine",
        label: "See Live",
    },
    {
        name: "Site of the day",
        type: "Awwwards",
        project: "Verse 21",
        label: "See Live",   
    },
    {
        name: "Developer Awards",
        type: "Awwwards",
        project: "LVXH - AMOT",
        label: "See Live",
    },
    {
        name: "Developer Awards",
        type: "Awwwards",
        project: "Silvia Santiago",
        label: "See Live",
    },
    {
        name: "Developer Awards",
        type: "Awwwards",
        project: "ArtisanCraft",
        label: "See Live",
    },
    {
        name: "Developer Awards",
        type: "Awwwards",
        project: "Disguised Edge",
        label: "See Live",
    },
    {
        name: "Developer Awards",
        type: "Awwwards",
        project: "2023 Showcase",
        label: "See Live",
    },
];